name: ant_logger
description: A starting point for Dart libraries or applications.
version: 0.0.1
homepage: https://github.com/928799934/ant_logger
author: lijian <928799934@qq.com>

environment:
  sdk: '>=2.5.0 <3.0.0'

#dependencies:

dev_dependencies:
  pedantic: ^1.8.0
  test: ^1.6.0
